import { EcommerceConfig } from "./src/types/ecommerce";

export const ecommerceConfig: EcommerceConfig = {
  store: {
    name: "Devsmith",
    tagline: "Precision Crafted Goods for Modern Living",
    description:
      "Minimalist design meets acoustic precision and ergonomic craftsmanship. Built for creative professionals, audiophiles, and discerning minds.",
    logoText: "Devsmith",
    logoBadge: "PRO",
    announcement: {
      enabled: true,
      text: "⚡ Flash Season Opening: Enjoy 20% off all studio acoustics & desk essentials with code",
      linkText: "DEVSMITH20",
      linkHref: "/products",
    },
    contact: {
      email: "concierge@devsmith.design",
      phone: "+1 (800) 555-0199",
      address: "742 Evergreen Terrace, Suite 400, San Francisco, CA 94107",
      supportHours: "Mon – Fri: 9:00 AM – 8:00 PM EST",
    },
    socialLinks: [
      { platform: "Twitter", url: "https://twitter.com", icon: "Twitter" },
      { platform: "Instagram", url: "https://instagram.com", icon: "Instagram" },
      { platform: "GitHub", url: "https://github.com", icon: "Github" },
      { platform: "YouTube", url: "https://youtube.com", icon: "Youtube" },
    ],
    currency: {
      code: "USD",
      symbol: "$",
      position: "prefix",
      decimals: 2,
    },
  },

  navigation: [
    { label: "Home", href: "/" },
    { label: "All Products", href: "/products" },
    { label: "Audio", href: "/products?category=audio" },
    { label: "Workspace", href: "/products?category=workspace" },
    { label: "Everyday Carry", href: "/products?category=everyday-carry" },
    { label: "Deals", href: "/products?sale=true", badge: "Sale" },
  ],

  hero: {
    badge: "New Fall Studio Collection 2026",
    headline: "Refined Engineering.",
    highlightedHeadline: "Sensory Simplicity.",
    subheadline:
      "Elevate your tactile and acoustic workspace with anodized aluminum, Japanese walnut, and studio-grade acoustics designed to disappear into your focus.",
    primaryCta: {
      label: "Explore Collection",
      href: "/products",
    },
    secondaryCta: {
      label: "View Featured Acoustics",
      href: "/products/aura-spatial-headphones",
    },
    stats: [
      { value: "50k+", label: "Happy Customers" },
      { value: "4.9/5", label: "Studio Rating" },
      { value: "100%", label: "Carbon Neutral" },
      { value: "2-Year", label: "Global Warranty" },
    ],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1400&auto=format&fit=crop",
    floatingCard: {
      title: "AURA Spatial Pro",
      subtitle: "Planar Magnetic Acoustic Drivers",
      rating: 4.95,
      price: "$349.00",
    },
  },

  perks: [
    {
      id: "shipping",
      title: "Complimentary Global Shipping",
      description: "Fast express dispatch on all orders over $75 with real-time tracking.",
      icon: "Truck",
    },
    {
      id: "warranty",
      title: "2-Year Zero-Hassle Warranty",
      description: "Direct manufacturer replacement and certified hardware peace of mind.",
      icon: "ShieldCheck",
    },
    {
      id: "returns",
      title: "30-Day Risk-Free Trial",
      description: "Experience our goods in your personal sanctuary. Free return shipping.",
      icon: "RefreshCw",
    },
    {
      id: "support",
      title: "Dedicated Audio Concierge",
      description: "Direct access to our sound engineers and technical support specialists.",
      icon: "Headphones",
    },
  ],

  categories: [
    {
      id: "audio",
      name: "Audio & Sound",
      slug: "audio",
      description: "Custom beryllium planar drivers, active noise cancellation, and neutral acoustic tuning.",
      image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop",
      icon: "Headphones",
      featured: true,
      productCount: 4,
    },
    {
      id: "workspace",
      name: "Workspace & Desk",
      slug: "workspace",
      description: "Precision CNC milled aluminum stands, wool felt pads, and tactile mechanical boards.",
      image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop",
      icon: "Laptop",
      featured: true,
      productCount: 4,
    },
    {
      id: "everyday-carry",
      name: "Everyday Carry",
      slug: "everyday-carry",
      description: "Ultra-compact titanium accessories, waterproof sleeves, and RFID-shielded leather goods.",
      image: "https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=800&auto=format&fit=crop",
      icon: "Briefcase",
      featured: true,
      productCount: 3,
    },
    {
      id: "wearables",
      name: "Smart Wearables",
      slug: "wearables",
      description: "Minimalist biometric rings, sapphire crystal timepieces, and silent haptic trackers.",
      image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop",
      icon: "Watch",
      featured: true,
      productCount: 3,
    },
  ],

  products: [
    {
      id: "aura-spatial-headphones",
      name: "AURA Spatial Pro Wireless Headphones",
      slug: "aura-spatial-headphones",
      price: 349,
      originalPrice: 399,
      category: "audio",
      description:
        "Engineered with 45mm custom planar magnetic drivers, adaptive hybrid ANC, and memory foam lambskin pads. Features lossless 24-bit/96kHz wireless streaming and 40-hour continuous battery life.",
      shortDescription: "Flagship wireless planar magnetic headphones with active hybrid noise cancellation.",
      rating: 4.9,
      reviewCount: 142,
      inStock: true,
      stockCount: 18,
      isFeatured: true,
      isNew: true,
      badge: "BESTSELLER",
      tags: ["wireless", "noise-canceling", "audiophile", "bluetooth-5.3"],
      images: [
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=1000&auto=format&fit=crop",
      ],
      colors: [
        { name: "Matte Slate", hex: "#1e293b", inStock: true },
        { name: "Silver Lunar", hex: "#e2e8f0", inStock: true },
        { name: "Desert Sand", hex: "#d7c4b7", inStock: true },
      ],
      features: [
        "45mm Planar Magnetic acoustic transducers",
        "Hybrid Adaptive Noise Cancellation with Transparency mode",
        "High-definition aptX Adaptive & LDAC audio codecs",
        "40 hours playback with USB-C quick recharge (15 mins = 6 hrs)",
        "Ultra-lightweight magnesium alloy chassis with magnetic cushions",
      ],
      specifications: [
        { label: "Frequency Response", value: "10Hz – 48,000Hz" },
        { label: "Impedance", value: "32 Ohms" },
        { label: "Weight", value: "278g" },
        { label: "Connectivity", value: "Bluetooth 5.3 + 3.5mm Analog" },
      ],
    },
    {
      id: "aura-tactile-keyboard",
      name: "AURA Horizon 75 Mechanical Keyboard",
      slug: "aura-tactile-keyboard",
      price: 199,
      originalPrice: 229,
      category: "workspace",
      description:
        "A gasket-mounted 75% mechanical typing instrument encased in solid CNC anodized aluminum. Equipped with factory-lubricated silent tactile switches, hot-swappable sockets, and sound-dampening brass plate.",
      shortDescription: "Gasket-mounted solid aluminum mechanical keyboard with hot-swappable tactile switches.",
      rating: 4.8,
      reviewCount: 98,
      inStock: true,
      stockCount: 24,
      isFeatured: true,
      badge: "STAFF PICK",
      tags: ["mechanical", "workspace", "ergonomic", "wireless"],
      images: [
        "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=1000&auto=format&fit=crop",
      ],
      colors: [
        { name: "Space Gray", hex: "#334155", inStock: true },
        { name: "Nordic Frost", hex: "#f1f5f9", inStock: true },
      ],
      features: [
        "CNC 6063 Anodized Aluminum chassis",
        "Gasket-mounted acoustic dampening with PORON foam",
        "Tri-mode connectivity: 2.4GHz wireless, Bluetooth, Type-C",
        "South-facing RGB with discrete ambient glow",
        "4000mAh battery lasting up to 200 hours without backlight",
      ],
      specifications: [
        { label: "Layout", value: "75% Compact (82 Keys)" },
        { label: "Switch Type", value: "Factory Lubed Tactile (45g)" },
        { label: "Keycaps", value: "Double-shot PBT Dye-sub" },
        { label: "Weight", value: "1,420g" },
      ],
    },
    {
      id: "aura-smart-watch",
      name: "Chronos Titanium Biometric Watch",
      slug: "aura-smart-watch",
      price: 279,
      originalPrice: 320,
      category: "wearables",
      description:
        "Grade 5 aerospace titanium bezel paired with anti-reflective sapphire glass. Continuous HRV, blood oxygen, sleep stage tracking, and discreet non-intrusive haptic notifications.",
      shortDescription: "Minimalist Grade 5 titanium smartwatch with biometric heart and sleep sensors.",
      rating: 4.7,
      reviewCount: 64,
      inStock: true,
      stockCount: 12,
      isFeatured: true,
      isNew: true,
      badge: "NEW",
      tags: ["smartwatch", "fitness", "titanium", "minimalist"],
      images: [
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=1000&auto=format&fit=crop",
      ],
      colors: [
        { name: "Titanium Raw", hex: "#94a3b8", inStock: true },
        { name: "Obsidian Black", hex: "#0f172a", inStock: true },
      ],
      features: [
        "Ultra-bright 1.43\" AMOLED with always-on mode",
        "Grade 5 Titanium bezel & scratchproof sapphire crystal",
        "Dual-frequency GNSS navigation for micro-accuracy",
        "14-day battery life on standard mode",
        "50m / 5ATM water resistance rating",
      ],
      specifications: [
        { label: "Display", value: "1.43\" AMOLED 466x466" },
        { label: "Battery Life", value: "Up to 14 days" },
        { label: "Water Resistance", value: "5 ATM (50m)" },
        { label: "Case Size", value: "42mm" },
      ],
    },
    {
      id: "aura-desk-mat",
      name: "Merino Wool & Italian Leather Desk Mat",
      slug: "aura-desk-mat",
      price: 69,
      category: "workspace",
      description:
        "Handcrafted dual-sided desk surface. High-density European merino wool felt on one side for soothing warmth, and vegetable-tanned full-grain Tuscan leather on the other for ultra-smooth optical mouse tracking.",
      shortDescription: "Reversible natural merino wool felt and vegetable-tanned leather desk protector.",
      rating: 4.9,
      reviewCount: 215,
      inStock: true,
      stockCount: 45,
      isFeatured: false,
      badge: "POPULAR",
      tags: ["workspace", "accessories", "leather", "minimal"],
      images: [
        "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1000&auto=format&fit=crop",
      ],
      sizes: [
        { name: "Medium (70 x 30 cm)", inStock: true },
        { name: "Large (90 x 40 cm)", inStock: true },
        { name: "Extended (105 x 50 cm)", inStock: true },
      ],
      features: [
        "100% genuine German merino wool felt",
        "Full-grain certified Tuscan vegetable-tanned leather",
        "Water-repellent nanocoating prevents liquid stains",
        "Precision burnished edge finishing prevents fraying",
      ],
      specifications: [
        { label: "Thickness", value: "4.5 mm" },
        { label: "Origin", value: "Crafted in Florence, Italy" },
      ],
    },
    {
      id: "aura-studio-earbuds",
      name: "AURA Pods Active True Wireless",
      slug: "aura-studio-earbuds",
      price: 189,
      originalPrice: 219,
      category: "audio",
      description:
        "True wireless in-ear monitors equipped with graphene diaphragms and dual noise-canceling beamforming microphones. Precision acoustic seal ensures immersive spatial staging wherever work takes you.",
      shortDescription: "Compact true-wireless earbuds with active noise reduction and spatial audio.",
      rating: 4.6,
      reviewCount: 88,
      inStock: true,
      stockCount: 30,
      isFeatured: true,
      badge: "SALE",
      tags: ["earbuds", "audio", "bluetooth", "compact"],
      images: [
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?q=80&w=1000&auto=format&fit=crop",
      ],
      colors: [
        { name: "Pebble White", hex: "#f8fafc", inStock: true },
        { name: "Midnight Onyx", hex: "#0f172a", inStock: true },
      ],
      features: [
        "11mm Graphene dynamic drivers for deep low-end response",
        "Active hybrid noise cancellation up to -42dB",
        "Qi wireless charging case with magnetic snap closure",
        "IPX5 sweat and rain water resistance",
        "32 hours combined total playtime",
      ],
      specifications: [
        { label: "Driver Size", value: "11mm Graphene Dynamic" },
        { label: "Earbud Playtime", value: "8 Hours (ANC On)" },
        { label: "Case Battery", value: "24 Additional Hours" },
        { label: "Protection", value: "IPX5 Certified" },
      ],
    },
    {
      id: "aura-mag-wallet",
      name: "Billet Titanium MagSafe Card Case",
      slug: "aura-mag-wallet",
      price: 59,
      category: "everyday-carry",
      description:
        "CNC machined from a solid billet of aerospace-grade titanium. Features strong neodymium N52 magnets for secure phone adhesion and RFID signal shielding for up to 6 cards.",
      shortDescription: "Ultra-slim RFID-blocking aerospace titanium cardholder with MagSafe snap.",
      rating: 4.8,
      reviewCount: 110,
      inStock: true,
      stockCount: 35,
      isFeatured: false,
      badge: "SLIM",
      tags: ["everyday-carry", "titanium", "magsafe", "edc"],
      images: [
        "https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=1000&auto=format&fit=crop",
      ],
      features: [
        "CNC milled aerospace grade titanium body",
        "Integrated dual-action thumb slot for instant card fan-out",
        "Built-in RFID/NFC frequency protection",
        "N52 rare-earth magnetic array with silicone anti-slip grip",
      ],
      specifications: [
        { label: "Card Capacity", value: "1 to 6 Cards + Folded Cash" },
        { label: "Weight", value: "48 grams" },
        { label: "Thickness", value: "7.2 mm" },
      ],
    },
    {
      id: "aura-laptop-stand",
      name: "Apex Ergonomic Aluminum Laptop Riser",
      slug: "aura-laptop-stand",
      price: 85,
      originalPrice: 99,
      category: "workspace",
      description:
        "Sculpted from a single sheet of bead-blasted 4mm aircraft aluminum. Angles your display to optimal ergonomic eye-level while maximizing passive convection airflow around notebook vents.",
      shortDescription: "Seamless 4mm aircraft aluminum laptop stand engineered for optimal neck posture.",
      rating: 4.9,
      reviewCount: 76,
      inStock: true,
      stockCount: 20,
      isFeatured: false,
      tags: ["workspace", "ergonomics", "aluminum", "minimal"],
      images: [
        "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1000&auto=format&fit=crop",
      ],
      colors: [
        { name: "Silver Anodized", hex: "#cbd5e1", inStock: true },
        { name: "Space Gray", hex: "#475569", inStock: true },
      ],
      features: [
        "Raises screen 6 inches for ergonomic neck and spine alignment",
        "Unibody 4mm aluminum acts as heat sink for cool CPU performance",
        "Cable routing pass-through keeps desktop clutter-free",
        "Anti-scratch non-marking silicone pads on contact points",
      ],
      specifications: [
        { label: "Compatibility", value: "MacBook & Laptops 11\" to 17\"" },
        { label: "Material", value: "Bead-blasted Anodized Aluminum" },
        { label: "Weight", value: "850g" },
      ],
    },
    {
      id: "aura-commute-backpack",
      name: "Aether 22L Weatherproof Commuter Pack",
      slug: "aura-commute-backpack",
      price: 185,
      originalPrice: 210,
      category: "everyday-carry",
      description:
        "Constructed with X-Pac waterproof sailcloth laminate and YKK AquaGuard weather-sealed zippers. Includes a dedicated suspended 16\" laptop chamber and modular magnetic key leashes.",
      shortDescription: "Ultra-durable X-Pac waterproof urban pack with suspended laptop compartment.",
      rating: 4.85,
      reviewCount: 52,
      inStock: true,
      stockCount: 14,
      isFeatured: true,
      badge: "STAFF PICK",
      tags: ["backpack", "commute", "waterproof", "travel"],
      images: [
        "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1546938576-6e6a64f317cc?q=80&w=1000&auto=format&fit=crop",
      ],
      features: [
        "Multi-layer waterproof X-Pac VX21 outer shell",
        "Floating plush-lined 16\" laptop sleeve with drop protection",
        "Fidlock V-buckle magnetic quick-release chest strap",
        "Luggage trolley pass-through back panel for seamless travel",
      ],
      specifications: [
        { label: "Capacity", value: "22 Liters" },
        { label: "Dimensions", value: "48 x 30 x 16 cm" },
        { label: "Weight", value: "980g" },
      ],
    },
  ],

  promoBanner: {
    badge: "Limited Season Promotion",
    title: "Upgrade Your Studio Setup",
    subtitle:
      "Claim 20% off all studio equipment, acoustic headphone drivers, and ergonomic desk gear when you checkout today.",
    discountCode: "DEVSMITH20",
    discountPercent: 20,
    ctaText: "Shop The Sale",
    ctaHref: "/products",
    expiresText: "Offer valid for limited inventory this week",
    image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=1000&auto=format&fit=crop",
  },

  testimonials: [
    {
      id: "1",
      name: "Marcus Vance",
      role: "Principal Product Designer at Metrix",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
      rating: 5,
      comment:
        "The AURA Spatial Pro headphones redefined my daily flow. The soundstage is remarkably spacious and neutral, while the industrial design feels like a museum piece on my desk.",
      verifiedBuyer: true,
      productPurchased: "AURA Spatial Pro",
    },
    {
      id: "2",
      name: "Elena Rostova",
      role: "Architect & Spatial Consultant",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop",
      rating: 5,
      comment:
        "Uncompromising attention to tactile quality. The Horizon 75 keyboard has the most satisfying keystroke feel I've experienced, and the anodized finish matches my workspace flawlessly.",
      verifiedBuyer: true,
      productPurchased: "AURA Horizon 75 Keyboard",
    },
    {
      id: "3",
      name: "Julian Chen",
      role: "Creative Director, Studio Monolith",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
      rating: 5,
      comment:
        "From the unboxing experience to daily carry, every detail has been obsessively considered. Shipping was rapid and customer support responded in under an hour.",
      verifiedBuyer: true,
      productPurchased: "Aether 22L Commuter Pack",
    },
  ],

  newsletter: {
    badge: "Exclusive Access",
    title: "Join The AURA Collective",
    subtitle:
      "Be the first to experience limited batch drops, private acoustic engineering notes, and seasonal member-only discounts.",
    placeholder: "Enter your email address...",
    buttonText: "Subscribe",
    perks: ["10% off your first order", "Early access to limited drops", "No spam, unsubscribe anytime"],
    disclaimer: "By subscribing you agree to our Terms of Service and Privacy Policy.",
  },

  footer: {
    columns: [
      {
        title: "Products",
        links: [
          { label: "All Collections", href: "/products" },
          { label: "Audio & Sound", href: "/products?category=audio" },
          { label: "Workspace & Desk", href: "/products?category=workspace" },
          { label: "Everyday Carry", href: "/products?category=everyday-carry" },
          { label: "Special Offers", href: "/products?sale=true" },
        ],
      },
      {
        title: "Customer Care",
        links: [
          { label: "Order Tracking", href: "#" },
          { label: "Shipping Policy", href: "#" },
          { label: "Returns & Exchanges", href: "#" },
          { label: "Warranty Coverage", href: "#" },
          { label: "Contact Concierge", href: "#" },
        ],
      },
      {
        title: "Company",
        links: [
          { label: "Our Story", href: "#" },
          { label: "Sustainability Manifesto", href: "#" },
          { label: "Materials & Craft", href: "#" },
          { label: "Studio Journal", href: "#" },
          { label: "Careers", href: "#" },
        ],
      },
      {
        title: "Legal",
        links: [
          { label: "Privacy Policy", href: "#" },
          { label: "Terms of Service", href: "#" },
          { label: "Cookie Preferences", href: "#" },
          { label: "Accessibility", href: "#" },
        ],
      },
    ],
    copyright: "© 2026 Devsmith Co. Built with DevSmith. All rights reserved.",
    paymentMethods: ["Visa", "Mastercard", "Amex", "Apple Pay", "Google Pay", "PayPal"],
  },
};
